### PR TITLE
Mutating field.

### PR DESCRIPTION
**Pull request by jvanz**
Adds the "mutating" field in the policy type to allow policy server checking if the policy evaluated is allowed to mutate the requests.

### CODE REVIEW

**Review by flavio — CHANGES_REQUESTED** [review]
Currently I'm not in favor of this change. I think we can avoid to do that and make the change only inside of the policy server (see my comments on https://github.com/kubewarden/policy-server/pull/139). But maybe I'm wrong and I didn't have enough :coffee: :)

**Review by ereslibre — CHANGES_REQUESTED** [review]
I also think this behavior (and settings) belongs exclusively to the policy-server, I would not introduce this logic here.

**Comment by flavio** [comment]
This is related with https://github.com/kubewarden/allow-privilege-escalation-psp-policy/issues/9

**Comment by jvanz** [comment]
After the latest changes at https://github.com/kubewarden/policy-server/pull/139, this is not necessary anymore

**Pull request closed without merging**
