### PR TITLE
feat: use docker_credential crate instead of DockerConfig

### LINKED ISSUE #169: Remove DockerConfig and use docker_credential crate instead
Adapt the code and consume latest [changes](https://github.com/kubewarden/policy-fetcher/pull/111) from policy-fetcher where docker_credential crate is used.

### PR DESCRIPTION
**Pull request by raulcabello**
Fix #169

### CODE REVIEW

**Review by flavio — CHANGES_REQUESTED** [review]
Overall OK, but this is not introducing the changes required to keep the cli flag and the env variable that are used to set the docker configuration file to work.

**Comment by raulcabello** [comment]
I was going to add the env var in [kwctl](https://github.com/kubewarden/kwctl/blob/main/src/main.rs#L415) and [policy-server](https://github.com/kubewarden/policy-server/blob/main/src/cli.rs#L282)

**Comment by flavio** [comment]
> I was going to add the env var in [kwctl](https://github.com/kubewarden/kwctl/blob/main/src/main.rs#L415) and [policy-server](https://github.com/kubewarden/policy-server/blob/main/src/cli.rs#L282)

my fault... I misread `policy-evaluator` with `policy-server` :facepalm:

**Review by flavio — APPROVED** [review]
LGTM, make sure you consume the right version of policy-fetcher

**Review by flavio — APPROVED** [review]
nit, can you please squash the 2 commits together? I would prefer to not leave traces inside of the history of your policy-fetcher fork

**Review by jvanz — APPROVED** [review]
LGTM! :D

**Pull request merged**
